#!/usr/bin/env sh

# load scripting-additions
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
# yabai -m config mouse_follows_focus on
# yabai -m config focus_follows_mouse autoraise
yabai -m config window_placement second_child
yabai -m config window_shadow off
# yabai -m config window_border on
# yabai -m config window_border_width 5
# yabai -m config active_window_border_color 0xffa35763
# yabai -m config normal_window_border_color 0xff353c54
# yabai -m config insert_feedback_color 0xaa7c5c9c
yabai -m config auto_balance off
yabai -m config split_ratio 0.50
yabai -m config window_gap 7

# general space layput
yabai -m config layout bsp

# padding
# padding_refresh_command="space_info=\$(yabai -m query --windows --space | jq)
# echo \"space_info: \$space_info\" >> \"\$HOME/yabailogs.txt\""

# yabai -m signal --add event=window_created action="$padding_refresh_command"
# yabai -m signal --add event=window_destroyed action="$padding_refresh_command"
"$HOME/.config/yabai/padding/setup.sh"

# mission-control desktop labels
yabai -m space 1 --label web
yabai -m space 2 --label code
yabai -m space 3 --label social
yabai -m space 4 --label mail
yabai -m space 5 --label media

# window rules
yabai -m rule --add app="^Firefox$" space=web
yabai -m rule --add app="^Emacs$" space=code manage=on
yabai -m rule --add app="^Telegram$" space=social
yabai -m rule --add app="^Slack$" space=social
yabai -m rule --add app="^Discord$" space=social
yabai -m rule --add app="^Spark$" space=mail manage=on
yabai -m rule --add app="^Transmission$" space=media
yabai -m rule --add app="^Spotify$" space=media manage=on
yabai -m rule --add app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add app="^Spotlight$" layer=above manage=off
yabai -m rule --add app="^Stickies$" manage=off
yabai -m rule --add app="^System Preferences$" layer=above manage=off

# signals
yabai -m signal --add event=window_destroyed action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
yabai -m signal --add event=application_terminated action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
